
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'SLR'

_lr_signature = 'AND ASPAS BOOLEAN COMMENT DIVIDE ELSE EQUAL FALSE GREATEQ GREATERTHAN ID IF LESSEQ LESSTHAN LPAREN MINUS NOTEQUAL NUMBER OR PAR PLUS RPAREN SEQ STRING TIMES TRUE WHILEstmts : stmtstmts : stmts stmtstmt : expressionexpression : expression PLUS term\n                  | expression MINUS term\n        term      : term TIMES factor\n                  | term DIVIDE factorexpression : termterm : factorfactor : NUMBERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'NUMBER':([0,1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,],[6,6,-1,-3,-8,-9,-10,6,-2,6,6,6,6,-4,-5,-6,-7,-11,]),'LPAREN':([0,1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,],[7,7,-1,-3,-8,-9,-10,7,-2,7,7,7,7,-4,-5,-6,-7,-11,]),'$end':([1,2,3,4,5,6,8,14,15,16,17,18,],[0,-1,-3,-8,-9,-10,-2,-4,-5,-6,-7,-11,]),'PLUS':([3,4,5,6,13,14,15,16,17,18,],[9,-8,-9,-10,9,-4,-5,-6,-7,-11,]),'MINUS':([3,4,5,6,13,14,15,16,17,18,],[10,-8,-9,-10,10,-4,-5,-6,-7,-11,]),'RPAREN':([4,5,6,13,14,15,16,17,18,],[-8,-9,-10,18,-4,-5,-6,-7,-11,]),'TIMES':([4,5,6,14,15,16,17,18,],[11,-9,-10,11,11,-6,-7,-11,]),'DIVIDE':([4,5,6,14,15,16,17,18,],[12,-9,-10,12,12,-6,-7,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'stmts':([0,],[1,]),'stmt':([0,1,],[2,8,]),'expression':([0,1,7,],[3,3,13,]),'term':([0,1,7,9,10,],[4,4,4,14,15,]),'factor':([0,1,7,9,10,11,12,],[5,5,5,5,5,16,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stmts","S'",1,None,None,None),
  ('stmts -> stmt','stmts',1,'p_stmts_stmt','mini_par_sint.py',6),
  ('stmts -> stmts stmt','stmts',2,'p_stmts_stmts_stmt','mini_par_sint.py',10),
  ('stmt -> expression','stmt',1,'p_stmt_expression','mini_par_sint.py',14),
  ('expression -> expression PLUS term','expression',3,'p_expression','mini_par_sint.py',18),
  ('expression -> expression MINUS term','expression',3,'p_expression','mini_par_sint.py',19),
  ('term -> term TIMES factor','term',3,'p_expression','mini_par_sint.py',20),
  ('term -> term DIVIDE factor','term',3,'p_expression','mini_par_sint.py',21),
  ('expression -> term','expression',1,'p_expression_term','mini_par_sint.py',32),
  ('term -> factor','term',1,'p_term_factor','mini_par_sint.py',44),
  ('factor -> NUMBER','factor',1,'p_factor_num','mini_par_sint.py',48),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','mini_par_sint.py',52),
]
